#!/usr/bin/env python3
"""Export a backtest strategy to TradingView Pine Script v6 or vnpy CtaTemplate.

Reads a backtest run directory (containing config.json and code/signal_engine.py)
and converts the Python signal logic to target platform code.

Use via Claude Code Bash tool::

    python scripts/export_strategy.py --run_dir ./my_run --format pine --output strategy.pine
    python scripts/export_strategy.py --run_dir ./my_run --format vnpy --output strategy.py

Config.json should contain: universe, symbols, interval, backtest_start, backtest_end.
Signal engine should have a ``generate(data_map)`` method.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from datetime import datetime
from pathlib import Path


def _load_run(run_dir: str) -> tuple[dict, str]:
    """Load config.json and signal_engine.py from a backtest run directory."""
    rd = Path(run_dir)
    config_path = rd / "config.json"
    engine_path = rd / "code" / "signal_engine.py"
    if not config_path.exists():
        raise FileNotFoundError(f"config.json not found in {run_dir}")
    if not engine_path.exists():
        raise FileNotFoundError(f"code/signal_engine.py not found in {run_dir}")
    config = json.loads(config_path.read_text())
    source = engine_path.read_text()
    return config, source


def _extract_strategy_info(config: dict, source: str) -> dict:
    """Parse strategy metadata from config and engine source."""
    # Extract class docstring
    doc_match = re.search(r'class\s+SignalEngine.*?:\s*\n\s*"""(.+?)"""', source, re.DOTALL)
    description = doc_match.group(1).strip() if doc_match else "Strategy exported by Vibe-Trading"

    # Extract parameter defaults from __init__
    params = {}
    init_match = re.search(r'def\s+__init__\s*\(self,\s*(.*?)\):', source, re.DOTALL)
    if init_match:
        args = init_match.group(1)
        for m in re.finditer(r'(\w+)\s*(?:=\s*([^,\n]+))?', args):
            name = m.group(1)
            if name in ("self", "data_map"):
                continue
            val = m.group(2)
            if val:
                val = val.strip().strip("'\"")
                try:
                    val = float(val) if "." in str(val) else int(val)
                except ValueError:
                    pass
            params[name] = val if val else None

    # Detect indicators from source
    indicators = []
    indicator_patterns = [
        (r'sma\(.*?(\d+)', 'SMA({})'),
        (r'ema\(.*?(\d+)', 'EMA({})'),
        (r'rsi\(.*?(\d+)', 'RSI({})'),
        (r'macd\(.*?(\d+).*?(\d+)', 'MACD({},{})'),
        (r'bollinger\(.*?(\d+)', 'Bollinger({})'),
        (r'atr\(.*?(\d+)', 'ATR({})'),
    ]
    for pattern, fmt in indicator_patterns:
        for m in re.finditer(pattern, source):
            indicators.append(fmt.format(*m.groups()))

    return {
        "description": description,
        "symbols": config.get("symbols", config.get("codes", ["UNKNOWN"])),
        "universe": config.get("universe", config.get("market", "unknown")),
        "interval": config.get("interval", "1D"),
        "start": config.get("backtest_start", ""),
        "end": config.get("backtest_end", ""),
        "parameters": params,
        "indicators": list(set(indicators)),
    }


# ---- Pine Script v6 Export ---------------------------------------------------

PINE_INDICATOR_MAP = {
    "SMA": "ta.sma", "EMA": "ta.ema", "RSI": "ta.rsi",
    "MACD": "ta.macd", "Bollinger": "ta.bb", "ATR": "ta.atr",
    "VWAP": "ta.vwap", "OBV": "ta.obv", "ADX": "ta.adx",
}


def _to_pine(info: dict, source: str) -> str:
    """Render Pine Script v6 strategy from backtest metadata."""
    sym = info["symbols"][0] if info["symbols"] else "BINANCE:BTCUSDT"
    params_block = "\n".join(
        f"    {k} = input.{'int' if isinstance(v, int) else 'float'}({v}, '{k}')"
        for k, v in info.get("parameters", {}).items()
        if v is not None
    )

    # Try to convert Python indicators to Pine equivalents
    pine_indicators = []
    for ind in info.get("indicators", []):
        for py_name, pine_name in PINE_INDICATOR_MAP.items():
            if ind.startswith(py_name):
                pine_indicators.append(f"    {ind.replace(py_name, pine_name)}")
                break

    template = f"""//@version=6
// Auto-generated by Vibe-Trading
// Export date: {datetime.now().strftime('%Y-%m-%d %H:%M')}
// Source run: {info['description']}
// Symbols: {info['symbols']}
// Interval: {info['interval']}

strategy("{info['description'][:50]}", overlay=true,
     initial_capital=100000, default_qty_type=strategy.percent_of_equity,
     default_qty_value=100, commission_type=strategy.commission.percent,
     commission_value=0.1)

// ── Inputs ──────────────────────────────────────────────────────────────────
{params_block or '    // (none)'}

// ── Indicators ──────────────────────────────────────────────────────────────
{'    '.join(pine_indicators) if pine_indicators else '    // Indicators detected in source:' + chr(10) + '    '.join(f'    // {i}' for i in info.get('indicators', []))}

// ── Entry / Exit Conditions ─────────────────────────────────────────────────
// TODO: Replace with actual signal logic extracted from signal_engine.py
// The Python source uses generate(data_map) → dict of signal DataFrames.
// Translate your condition logic below:

long_condition = ta.crossover(ta.sma(close, 10), ta.sma(close, 30))
short_condition = ta.crossunder(ta.sma(close, 10), ta.sma(close, 30))

if long_condition
    strategy.entry("Long", strategy.long)

if short_condition
    strategy.close("Long")

// ── Risk Management ─────────────────────────────────────────────────────────
// Optional: stop-loss, take-profit, trailing stop
// strategy.exit("XL", "Long", loss=200, profit=400)

// ── Alerts ──────────────────────────────────────────────────────────────────
// alertcondition(long_condition, title="Long Entry", message="Long signal!")
// alertcondition(short_condition, title="Exit", message="Exit signal!")
"""
    return template


# ---- vnpy Export -------------------------------------------------------------

def _to_vnpy(info: dict, source: str) -> str:
    """Render vnpy CtaTemplate from backtest metadata."""
    strategy_name = re.sub(r'[^a-zA-Z0-9_]', '', info["description"][:30].replace(" ", "_"))
    sym = info["symbols"][0] if info["symbols"] else "000001.SZSE"

    params_block = "\n".join(
        f"    {k}: {'int' if isinstance(v, int) else 'float'} = {v}"
        for k, v in info.get("parameters", {}).items()
        if v is not None
    )
    param_names = [k for k, v in info.get("parameters", {}).items() if v is not None]

    template = f'''"""
Vibe-Trading → vnpy export: {info["description"]}
Export date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
vt_symbol: {sym}
"""

from vnpy.app.cta_strategy import (
    CtaTemplate,
    StopOrder,
    TickData,
    BarData,
    TradeData,
    OrderData,
    BarGenerator,
    ArrayManager,
)


class {strategy_name}Strategy(CtaTemplate):
    """{info["description"]}"""

    author = "Vibe-Trading"

    # ── Parameters ────────────────────────────────────────────────────────
{params_block or '    # (none)'}

    parameters = {json.dumps(param_names)}

    # ── Variables ──────────────────────────────────────────────────────────
{chr(10).join(f'    {k}_val: float = 0.0' for k in param_names) if param_names else '    # (none)'}

    variables = [{', '.join(f'"{k}_val"' for k in param_names)}]

    def __init__(self, cta_engine, strategy_name, vt_symbol, setting):
        super().__init__(cta_engine, strategy_name, vt_symbol, setting)
        self.bg = BarGenerator(self.on_bar)
        self.am = ArrayManager()
        # TODO: Set warmup based on max indicator window

    def on_init(self):
        self.write_log("Strategy initialised")
        self.load_bar(60)

    def on_start(self):
        self.write_log("Strategy started")
        self.put_event()

    def on_stop(self):
        self.write_log("Strategy stopped")

    def on_tick(self, tick: TickData):
        self.bg.update_tick(tick)

    def on_bar(self, bar: BarData):
        self.cancel_all()
        am = self.am
        am.update_bar(bar)
        if not am.inited:
            return

        # ── Indicators ──────────────────────────────────────────────────────
        # TODO: Compute indicators using am.sma(), am.ema(), etc.
        # See the skills/vnpy-export/scripts/cta_template.py reference.

        # ── Signal Logic ────────────────────────────────────────────────────
        # TODO: Translate your generate() logic here.

        # cross_over = self.fast_val > self.slow_val and ...
        # if cross_over:
        #     if self.pos == 0:
        #         self.buy(bar.close_price, 1)

        self.put_event()

    def on_order(self, order: OrderData):
        pass

    def on_trade(self, trade: TradeData):
        self.put_event()

    def on_stop_order(self, stop_order: StopOrder):
        pass
'''
    return template


# ---- Main --------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Export backtest strategy to Pine Script or vnpy")
    parser.add_argument("--run_dir", required=True, help="Backtest run directory (contains config.json + code/signal_engine.py)")
    parser.add_argument("--format", required=True, choices=["pine", "vnpy"], help="Target platform")
    parser.add_argument("--output", required=True, help="Output file path")
    args = parser.parse_args()

    config, source = _load_run(args.run_dir)
    info = _extract_strategy_info(config, source)

    print(f"Strategy: {info['description']}", file=sys.stderr)
    print(f"Symbols: {info['symbols']}", file=sys.stderr)
    print(f"Parameters: {info['parameters']}", file=sys.stderr)
    print(f"Indicators detected: {info['indicators']}", file=sys.stderr)

    if args.format == "pine":
        out = _to_pine(info, source)
    else:
        out = _to_vnpy(info, source)

    Path(args.output).write_text(out, encoding="utf-8")
    print(f"Exported to {args.output} ({len(out)} bytes)")


if __name__ == "__main__":
    main()
